### ISSUE TITLE
mount resource should be unique

### ISSUE THREAD

**Issue by cpumichael** [petems/puppet-swap_file#14]
This is similar to the issue with being able to resize a swapfile.

If `mount { 'swap': ... }` was changed to `mount { $swapfile: ... }`, then multiple swapfiles could be created or an old one could be changed to `ensure=>absent`, and a new one with a different size could be created.

**Comment by petems** [comment]
Yep, I also rather rashly declared the swapfile as a class rather than a defined type, so you can only use it once!

I'm looking to fix this soon! :+1:

**Comment by petems** [comment]
@cpumichael This is now fixed and released on the forge as 1.1.1 :+1:
