### ISSUE TITLE
swap_file::files fails when you set the ensure attribute to absent

### ISSUE THREAD

**Issue by carvid** [petems/puppet-swap_file#21]
Set the ensure attribute to absent always fail because the `Exec[Detach swap file ...]` dependency could not be found. I suspect the offender are the single quotes for interpolate `$swapfile` value in the title of the resource (https://github.com/petems/puppet-swap_file/blob/master/manifests/files.pp#L72).

**Comment by petems** [comment]
Resolved in in #22
