### ISSUE TITLE
dd vs fallocate 

### ISSUE THREAD

**Issue by BIAndrews** [petems/puppet-swap_file#26]
In my quick test `dd` ran for almost 3 minutes to create a 4GB file. However `fallocate` ran for 0.09 seconds and worked perfect. I would like to add a parameter to `swap_file` allowing user choice of which tool to use to create the swap file, dd remaining default. There seems to be issues with fallocate on XFS so it would be important for the old `dd` command to remain default. This is an important issue for AWS EC2 users since I/O can be limited and using a file for swap is much easier and more efficient on instances. 

Thoughts?

**Comment by petems** [comment]
PR here: #29 

Main issue: warning people about issues with XFS.

Solution: fail("$::filesystems is XFS. Fallocate doesn't work on XFS")

Will add this to the PR

**Comment by BIAndrews** [comment]
The problem with just checking $::filesystems for xfs is that you can't tell what path is the XFS partition. For example AWS CentOS6 defaults to ex4 root. However if you mount another EBS volume for additional data XFS is a common choice for that. With this solution just having an additional XFS volume anywhere will cause swap_file to fail when it normally shouldn't. 

I recommend just leaving a good warning in the readme under usage. As long as the default of `dd` is kept the user has to decide to use `cmd => 'fallocate'` which comes with the caveat about XFS swap file destinations. But at least it's up to the puppet profile author.

**Comment by BIAndrews** [comment]
basedir="/tank"
`df -PT $basedir | awk 'NR==2 {print $2}' | grep xfs`

This will exit 0 if it is xfs, that could be used as a way to automatically detect the paths filesystem type with more testing. exec with an unless=> command I'm thinking.

**Comment by petems** [comment]
Yeah, I think the facter stuff might get into YAGNI teritory. 

I'll put a warning in the readme and in the actual code itself :+1:

**Comment by BIAndrews** [comment]
If you want to give me a minute I might have an inline tested solution using onlyif=> on the fallocate option. I'm almost done now just testing things. I'm not sure how to write a spec file for this. I'm not very experienced with rspec.

**Comment by petems** [comment]
No problem, push something up and I'll 

I'm eventually going to move all the file creation logic into a new module called file_maker or something, then I can get rid of the exec's completely :+1:

**Comment by petems** [comment]
Fixed by https://github.com/petems/puppet-swap_file/pull/35
