### ISSUE TITLE
Release version 2.1.0 on Puppet Forge

### ISSUE THREAD

**Issue by mbrodala** [petems/puppet-swap_file#36]
The latest available version on [Puppet Forge](https://forge.puppetlabs.com/petems/swap_file) currently is 2.0.0 but in VCS it is 2.1.0. Please release version 2.1.0 on Puppet Forge too.

**Comment by mbrodala** [comment]
Also consider integrating [puppet-blacksmith](https://github.com/voxpupuli/puppet-blacksmith) to automate this.

**Comment by petems** [comment]
Released: https://forgeapi.puppetlabs.com/v3/files/petems-swap_file-2.1.0.tar.gz

**Comment by mbrodala** [comment]
Thanks. :-)
