### ISSUE TITLE
Module should be tested on multiple Ruby and Puppet versions

### ISSUE THREAD

**Issue by Phil-Friderici** [petems/puppet-swap_file#38]
I would like to modify travis testing to test the module against multiple Ruby and Puppet versions.
See [1] for an example how this would look like, see [2] for a quick&dirty hack to enabled that.

[1] https://travis-ci.org/Phil-Friderici/puppet-swap_file/builds/101036980 
[2] https://github.com/Phil-Friderici/puppet-swap_file/pull/1

**Comment by petems** [comment]
Sounds good to me, if you want to clean it up and put it in a merge request I can merge :smile:

**Comment by Phil-Friderici** [comment]
Sweet, will cleanup the changes and prepare them to be mergeable

**Comment by Phil-Friderici** [comment]
merged with https://github.com/petems/puppet-swap_file/pull/39
@petems: Thanks !
